name: Release databases

on:
  schedule:
    - cron: "0 13 * * 1" # "At 13:00 on Monday."
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync

      - name: Get original db
        run: uv run python spam_db/create_database.py ${{ secrets.ORIGINAL_SOURCE }} sia_orig original.csv

      - name: Get fork db
        run: uv run python spam_db/create_database.py ${{ secrets.FORK_SOURCE }} sia_fork fork.csv

      - name: Set tag and release name
        run: |
          current_date=$(date +'%Y-%m-%d')
          echo "Current Date: $current_date"
          echo "RELEASE_TAG=$current_date" >> "$GITHUB_ENV"
          echo "RELEASE_NAME=$current_date" >> "$GITHUB_ENV"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          files: |
            filtered_original.csv
            filtered_fork.csv
            original.csv
            fork.csv
